// 생성물 — 손으로 고치지 마세요. 원본: prisma/sql/arcadeSearchPage.sql
// source-sha256: 4c4636064b857a5b53c290d17c830976ca9c4d93e655f6804708b068a2698af1
// 다시 만들기: npm run db:prisma:sql (DB 필요) · 대조: npm run db:prisma:sql:check (DB 불필요)

/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param lat
 * @param lng
 * @param _text
 * @param _int4
 * @param radiusKm
 * @param arcadeId
 * @param _int4
 * @param limit
 * @param offset
 */
export const arcadeSearchPage = $runtime.makeTypedQueryFactory("WITH scored AS (\nSELECT a.id, a.name, a.address, a.lat, a.lng, a.open_time, a.close_time, a.is_24h,\na.phone, a.note, a.homepage, a.rating_avg, a.review_count,\nCASE WHEN $1::float8 IS NULL OR $2::float8 IS NULL THEN NULL ELSE\n6371 * acos(LEAST(1, GREATEST(-1,\ncos(radians($1::float8)) * cos(radians(a.lat))\n* cos(radians(a.lng) - radians($2::float8))\n+ sin(radians($1::float8)) * sin(radians(a.lat))\n)))\nEND AS distance_km\nFROM arcades a\nWHERE ($6::int IS NULL OR a.id = $6::int)\nAND (cardinality($7::int[]) = 0 OR a.id = ANY($7::int[]))\nAND ($1::float8 IS NULL OR $2::float8 IS NULL OR $5::float8 IS NULL\nOR (a.lat BETWEEN $1::float8 - $5::float8 / 110.0 AND $1::float8 + $5::float8 / 110.0\nAND a.lng BETWEEN $2::float8 - $5::float8 / (110.0 * GREATEST(cos(radians($1::float8)), 0.01))\nAND $2::float8 + $5::float8 / (110.0 * GREATEST(cos(radians($1::float8)), 0.01))))\nAND (cardinality($3::text[]) = 0\nOR (SELECT bool_and(a.name ILIKE '%' || t || '%' OR a.address ILIKE '%' || t || '%')\nFROM unnest($3::text[]) AS t))\nAND (cardinality($4::int[]) = 0 OR a.id IN (\nSELECT am.arcade_id\nFROM arcade_machines am\nWHERE am.machine_id = ANY($4::int[])\nGROUP BY am.arcade_id\nHAVING COUNT(DISTINCT am.machine_id) = (SELECT COUNT(DISTINCT x) FROM unnest($4::int[]) AS x)\n))\n),\nbase AS (\nSELECT * FROM scored s\nWHERE $5::float8 IS NULL OR s.distance_km IS NULL OR s.distance_km <= $5::float8\n),\ncounted AS (\nSELECT b.id, b.distance_km, b.name, (COUNT(*) OVER ())::int AS total_count\nFROM base b\n)\nSELECT c.id, c.total_count\nFROM counted c\nORDER BY c.distance_km ASC NULLS LAST, c.name ASC, c.id ASC\nLIMIT $8::int OFFSET $9::int;") as (lat: number | null, lng: number | null, _text: string[], _int4: number[], radiusKm: number | null, arcadeId: number | null, _int4: number[], limit: number, offset: number) => $runtime.TypedSql<arcadeSearchPage.Parameters, arcadeSearchPage.Result>

export namespace arcadeSearchPage {
  export type Parameters = [lat: number | null, lng: number | null, _text: string[], _int4: number[], radiusKm: number | null, arcadeId: number | null, _int4: number[], limit: number, offset: number]
  export type Result = {
    id: number
    total_count: number | null
  }
}
